Logistica/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include(('base.urls', 'base'), namespace='base')),
    path('inventario/', include(('inventario.urls', 'inventario'), namespace='inventario')),# Llama achivo url de la aplicacion
    path('admin/', admin.site.urls),
]

base/urls.py
from django.urls import path
# Vistas por defect para login y logout
from django.contrib.auth import views as auth_views

from base.views import Home

urlpatterns = [

    path('', Home.as_view(), name='home'),
    # Ruta para login
    path('login/', auth_views.LoginView.as_view(template_name='login/login.html'), name='login'),
    # Ruta para logout
    path('logout/', auth_views.LogoutView.as_view(template_name='login/login.html'), name='logout')

]

inventario/urls.py
from django.urls import path

from inventario.views import *

urlpatterns = [

    path('tipoTransporte/', TipoTransporteListView.as_view(), name='tipoTransporte'),  # URL de aplicacion

]

base/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from django.template.defaultfilters import default


# Clase general del sistema
class ClaseModelo(models.Model):
    estado = models.IntegerField(default=1)
    fecha_guardado = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True, null=True)
    usuario_grabacion = models.ForeignKey(User, on_delete=models.CASCADE)
    usuario_modifica = models.IntegerField(blank=True, null=True)

    class Meta:
        abstract = True

inventario/models.py
from select import select

from django.db import models
from django.forms import model_to_dict

from base.models import ClaseModelo


class TipoTransporte(ClaseModelo):
    nombre = models.CharField(
        max_length=60,
        help_text='Nombre del tipo de transporte',
        unique=True
    )

    def toJSON(self):  # Retorna JSON
        item = model_to_dict(self)
        return item

    def _str_(self):
        return '{}'.format(self.nombre)

    def save(self):  # Guarda en mayuscula
        self.nombre = self.nombre.upper()
        super(TipoTransporte, self).save()

    class Meta:
        verbose_name_plural = 'TipoTransportes'

base/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect

from django.contrib.auth.mixins import LoginRequiredMixin  # Mixin para authentication de usuario
from django.views import generic


class Home(LoginRequiredMixin, generic.TemplateView):

    template_name = 'braket/layout.html'
    login_url = '/login'  # si el usuario no esta autenticado envia a login

inventario/views.py
from logging import exception

from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView

from inventario.models import TipoTransporte

""" index para mostrar vista de tipo de transporte"""


# Vista basada en clase
class TipoTransporteListView(ListView):
    model = TipoTransporte
    template_name = 'catalogos/tipoTransporte.html'

    @method_decorator(csrf_exempt)  # Decorador para omitir token
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'getdata':
                data = []
                for i in TipoTransporte.objects.all():
                    data.append(i.toJSON())
            else:
                data['error'] = 'Ha ocurrido un error'
        except exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)  # serializando objetos que no son diccionario

templates/braket/aside.html
<!-- ########## START: ASIDE ########## -->
<div class="br-logo"><a href="/"><span>[</span>LDCI<span>]</span></a></div>
<div class="br-sideleft overflow-y-auto ps ps--theme_default ps--active-x ps--active-y">
  <label class="sidebar-label pd-x-15 mg-t-20">Navigation</label>
  <div class="br-sideleft-menu">


            <a href="catalogos.usuarios" class="optionMenu br-menu-link">
              <div class="br-menu-item">
                <i class="menu-item-icon icon ion-person-stalker tx-22"></i>
                <span class="menu-item-label">Usuarios</span>
              </div><!-- menu-item -->
            </a><!-- br-menu-link -->
            <a href="vendedor.vendedor" class="optionMenu br-menu-link">
              <div class="br-menu-item">
                <i class="menu-item-icon icon ion-person tx-24"></i>
                <span class="menu-item-label">Vendedores</span>
              </div><!-- menu-item -->
            </a><!-- br-menu-link -->

            <a href="cliente.cliente" class="optionMenu br-menu-link">
              <div class="br-menu-item">
                <i class="menu-item-icon icon ion-man tx-20"></i>
                <span class="menu-item-label">Clientes</span>
              </div><!-- menu-item -->
            </a><!-- br-menu-link -->
            <a href="" class="br-menu-link">
              <div class="br-menu-item">
                <i class="menu-item-icon icon ion-document-text tx-24"></i>
                <span class="menu-item-label">Facturacion</span>
                <i class="menu-item-arrow fa fa-angle-down"></i>
              </div><!-- menu-item -->
            </a><!-- br-menu-link -->
            <ul class="br-menu-sub nav flex-column">
              <li class="nav-item"><a href="factura.verFactura" class="optionMenu nav-link">Ver Facturas</a></li>
              <li class="nav-item"><a href="factura.generarFactura" class="optionMenu nav-link">Generar factura</a></li>
              <li class="nav-item"><a href="factura.crearFactura" class="optionMenu nav-link">Crear factura</a></li>
            </ul>
              <a href="" class="br-menu-link">
                  <div class="br-menu-item">
                      <i class="menu-item-icon fa fa-tags tx-24"></i>
                      <span class="menu-item-label">Entradas</span>
                      <i class="menu-item-arrow fa fa-angle-down"></i>
                  </div><!-- menu-item -->
              </a><!-- br-menu-link -->
              <ul class="br-menu-sub nav flex-column">
                  <li class="nav-item"><a href="entrada.entrada" class="optionMenu nav-link">Agregar</a></li>
              </ul>
            <a href="" class="br-menu-link">
              <div class="br-menu-item">
                <i class="menu-item-icon icon ion-clipboard tx-24"></i>
                <span class="menu-item-label">Cotizaciones</span>
                  <i class="menu-item-arrow fa fa-angle-down"></i>
              </div><!-- menu-item -->
            </a><!-- br-menu-link -->
              <ul class="br-menu-sub nav flex-column">
                  <li class="nav-item"><a href="cotizacion.cotizacion" class="optionMenu nav-link">Agregar</a></li>
                  <li class="nav-item"><a href="cotizacion.verCotizacion" class="optionMenu nav-link">Ver</a></li>
                  <li class="nav-item"><a href="cotizacion.seguimiento" class="optionMenu nav-link">Seguimiento</a></li>
              </ul>
            <a href="rastreo.rastreo" class="optionMenu br-menu-link">
              <div class="br-menu-item">
                <i  class="menu-item-icon icon ion-location tx-20"></i>
                <span class="menu-item-label">Rastreo</span>
              </div><!-- menu-item -->
            </a>
            <a href="" class="br-menu-link">
              <div class="br-menu-item">
                <i class="menu-item-icon fa fa-briefcase tx-24"></i>
                <span class="menu-item-label">Catalogos</span>
                  <i class="menu-item-arrow fa fa-angle-down"></i>
              </div><!-- menu-item -->
            </a><!-- br-menu-link -->
              <ul class="br-menu-sub nav flex-column">
                  <li class="nav-item"><a href="{% url 'inventario:tipoTransporte' %}" class="nav-link">Tipo Transporte</a></li>
                  <li class="nav-item"><a href="catalogos.tipoMercancia" class="optionMenu nav-link">Tipo Mercancia</a></li>
                  <li class="nav-item"><a href="catalogos.proveedor" class="optionMenu nav-link">Proveedores</a></li>
                  <li class="nav-item"><a href="catalogos.producto" class="optionMenu nav-link">Productos</a></li>
                  <li class="nav-item"><a href="catalogos.tipoModoTransporte" class="optionMenu nav-link">Modo Transporte</a></li>
              </ul>
              <a href="" class="br-menu-link">
                  <div class="br-menu-item">
                      <i class="menu-item-icon icon ion-archive tx-20"></i>
                      <span  class=" menu-item-label">Reportes</span>
                      <i class="menu-item-arrow fa fa-angle-down"></i>
                  </div><!-- menu-item -->
              </a>
                  <ul class="br-menu-sub nav flex-column">
                      <li class="nav-item"><a style="color: #adb5bd" onclick="rpt_vendedores()" class="nav-link">Vendedores</a></li>
                      <li class="nav-item"><a style="color: #adb5bd" onclick="rpt_clientes()" class=" nav-link">Clientes</a></li>
                      <li class="nav-item"><a style="color: #adb5bd" onclick="rpt_productos()" class=" nav-link">Productos</a></li>
                      <li class="nav-item"><a href="" class=" nav-link">Otros</a></li>
                  </ul>
              <a href="" target="_blank" class="br-menu-link">
                  <div class="br-menu-item">
                      <i  class="menu-item-icon icon ion-help tx-20"></i>
                      <span class="menu-item-label">Help</span>
                  </div><!-- menu-item -->
              </a>
  </div><!-- br-sideleft-menu -->

  <br>
</div><!-- br-sideleft -->
<!-- ########## END: ASIDE ########## -->

<script>

</script>

templates/braket/header.html
 <!-- ########## START: HEADER ########## -->
 <div class="br-header">
    <div class="br-header-left">
      <div class="navicon-left hidden-md-down"><a id="btnLeftMenu" href=""><i class="icon ion-navicon-round"></i></a></div>
      <div class="navicon-left hidden-lg-up"><a id="btnLeftMenuMobile" href=""><i class="icon ion-navicon-round"></i></a></div>
    </div><!-- br-header-left -->

     <div class="br-header-right">
         <nav class="nav">
             <span class="logged-name hidden-md-down">Tasa de cambio: <label id="lbl_tasa_cambio"></label></span>
         </nav>
     </div>

    <div class="br-header-right">
      <nav class="nav">
        <div class="dropdown">
          <a href="" class="nav-link nav-link-profile" data-toggle="dropdown">
            <span class="logged-name hidden-md-down">{{ user.get_username }}</span> {# Recupera el nombre del usuario en session #}
            <img src="https://www.flaticon.com/svg/static/icons/svg/1828/1828328.svg" class="wd-32 rounded-circle" alt="">
            <span class="square-10 bg-success"></span>
          </a>
          <div class="dropdown-menu dropdown-menu-header wd-200">
            <ul class="list-unstyled user-profile-nav">
              <li><a onclick="editarUsuario()" data-toggle="modal" data-target="#editar_Usuario" ><i class="icon ion-ios-person"></i> Editar</a></li>
              <li><a href="{% url 'base:logout' %}"><i class="icon ion-power"></i>Cerrar sesion</a></li>
            </ul>
          </div><!-- dropdown-menu -->
        </div><!-- dropdown -->
      </nav>
      <div class="navicon-right">
        <a id="btnRightMenu" href="" class="pos-relative">
          <i  class="icon ion-ios-calendar-outline tx-24"> </i>
        </a>
      </div>
    </div><!-- br-header-right -->
  </div><!-- br-header -->

  <!-- ########## END: HEADER ########## -->

templates/braket/layout.html
{%load static  %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
      <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Meta -->
    <meta name="description" content="SISTEMA - LOGISTICA DE CARGA">
    <meta name="author" content="kennysaenz31@gmail.com">

    <title>SISTEMA - LOGISTICA DE CARGA</title>
    <link rel="icon" href={% static 'assets/bracket/Logo-Intermodal.ico' %}>
    <link rel="stylesheet" href={% static 'assets/bracket/css/bracket.css' %}>
    <!-- vendor css -->
    <link rel="stylesheet" href={% static 'assets/bracket/lib/font-awesome/css/font-awesome.css' %}>
    <link rel="stylesheet" href={% static 'assets/bracket/lib/Ionicons/css/ionicons.css' %}>
    <link rel="stylesheet" href={% static 'assets/bracket/lib/perfect-scrollbar/css/perfect-scrollbar.css' %}>
    <link rel="stylesheet" href={% static 'assets/bracket/lib/jquery-switchbutton/jquery.switchButton.css' %}>
    <link rel="stylesheet" href={% static 'assets/bracket/lib/select2/css/select2.min.css' %}>

    <!-- Core DATABLE -->
    <link rel="stylesheet" href={% static 'LDCI/Core/core.css' %}>
    <link rel="stylesheet" href={% static 'LDCI/Core/dataTables.bootstrap.min.css' %}>
    <link rel="stylesheet" href={% static 'LDCI/Core/bootstrap.scss' %}>

     <!-- Core CSS -->
      <link rel="stylesheet" href={% static 'LDCI/Core/alertify.default.css' %}>
      <link rel="stylesheet" href={% static 'LDCI/Core/alertify.core.css' %}>
     <link rel="stylesheet" href={% static 'LDCI/Core/jquery-ui.min.css' %}>

      <link rel="stylesheet" href={% static 'LDCI/Core/intlTelInput.css' %}>
      <link rel="stylesheet" href={% static 'LDCI/Core/demo.css' %}>
      <link rel="stylesheet" href={% static 'LDCI/Core/avilon.css' %}>
      <link rel="stylesheet" href={% static 'LDCI/Core/dropzone.min.css' %}>

      <style>
          @media (min-width: 576px)
          {
              .br-sideleft {
                  z-index: 2000!important;
              }
          }

      </style>

  </head>
  <body>
     <!--Inicio Header -->
    {# @include('InicioSesion.editarUsuario') #}
     {% include "braket/header.html" %}
     {% include "braket/tabPanel.html" %}

     <!--Fin-->
     <!--Inicio Aside -->
     {% include "braket/aside.html" %}
     <!--Fin -->

     <!--INICIO CONTENEDOR CARGANDO-->
    <div id="loader-wrapper">
      <div id="loader"></div>
      <div class="loader-section section-left"></div>
      <div class="loader-section section-right"></div>
    </div>
    <!--FIN CONTENEDOR CARGANDO-->

    <div class="br-mainpanel">
      <div class="br-section-wrapper">
            <div id="principal" class="row"><!-- Agrega contenido desde otra vista-->
            {% csrf_token %}
                {% block principal %}

                    <section style="margin-top: 3%; width: 100%;" id="features">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-4 features-img">
                                    <img class="img-fluid" src={% static 'LDCI/img/Layout.png' %} alt="" class="wow fadeInLeft" style="    max-width: 150%!important; margin-left: -30%; padding-top: 50%; visibility: visible; animation-name: fadeInLeft;">
                                </div>
                                <div class="col-md-8" >
                                    <div class="col-md-12" style="margin-left: 10%;">
                                        <div class="section-header wow fadeIn" data-wow-duration="1s" style="visibility: visible; animation-duration: 1s; animation-name: fadeIn;">
                                            <h3 class="section-title">Productos / Servicio</h3>
                                            <span class="section-divider"></span>
                                        </div>
                                    </div>
                                    <div class="col-md-12" style="margin-left: 15%;">

                                        <div class="row">

                                            <div class="col-md-6 fadeInRight" style="width: 90%!important;  visibility: visible; animation-name: fadeInRight;">
                                                <div class="icon"><i class="ion-plane"></i></div>
                                                <h4 class="title"><a href="">Transporte Aéreo</a></h4>
                                                <p class="description">Embarques directos con cualquier línea aérea carguera y pasajero</p>
                                                <p class="description">Carga consolidada desde cualquier origen/destino</p>
                                                <p class="description">Itinerarios, tiempo de tránsito y servicios pre-establecidos</p>
                                                <p class="description"> Tarifas económicas y competitivas</p>
                                            </div>
                                            <div class="col-md-6 fadeInRight" data-wow-delay="0.1s" style="width: 90%!important; visibility: visible; animation-delay: 0.1s; animation-name: fadeInRight;">
                                                <div class="icon"><i class="ion-model-s"></i></div>
                                                <h4 class="title"><a href="">Transporte Terrestre</a></h4>
                                                <p class="description"> Embarques en camiones completos, furgón, rastras</p>
                                                <p class="description"> Embarques de mercaderías extra-dimensionales y pesadas en equipos Low Boys o plataformas</p>
                                                <p class="description"> Embarques consolidados en Centroamérica, México y Panamá con horarios publicados</p>
                                            </div>
                                            <div class="col-md-6 fadeInRight" data-wow-delay="0.2s" style="width: 90%!important; visibility: visible; animation-delay: 0.2s; animation-name: fadeInRight;">
                                                <div class="icon"><i class="ion-android-compass"></i></div>
                                                <h4 class="title"><a href="">Transporte Marítimo</a></h4>
                                                <p class="description">Contenedores completos FCL/FCL</p>
                                                <p class="description">Carga consolidada LCL/LCL desde cualquier origen/destino hasta Managua y viceversa</p>
                                                <p class="description">Itinerarios, tiempo de tránsito y servicios pre-establecidos</p>
                                                <p class="description"> Tarifas económicas y competitivas</p>
                                            </div>
                                            <div class="col-md-6 fadeInRight" data-wow-delay="0.3s" style="width: 90%!important; visibility: visible; animation-delay: 0.3s; animation-name: fadeInRight;">
                                                <div class="icon"><i class="ion-ios-analytics-outline"></i></div>
                                                <h4 class="title"><a href="">Gelpack y Hielo Seco</a></h4>
                                                <p class="description">Tenemos a la venta de Gel Pack como refrigerante para
                                                    mantener la temperatura de su carga perecedera,
                                                    importado directamente de USA</p>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>

                {% endblock %}
            </div>
            <footer class="br-footer">
              <div class="footer-left">
                  <div class="mg-b-2" id="copyright"></div>
              </div>
            </footer>
      </div>
    </div><!-- br-mainpanel -->


    <script src={% static 'assets/bracket/lib/jquery/jquery.js' %}></script>
    <script src={% static 'assets/bracket/lib/popper/popper.js' %}></script>
    <script src={% static 'assets/bracket/lib/bootstrap/bootstrap.js' %}></script>
    <script src={% static 'assets/bracket/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.js' %}></script>
    <script src={% static 'assets/bracket/lib/moment/moment.js' %}></script>
    <script src={% static 'assets/bracket/lib/jquery-ui/jquery-ui.js' %}></script>
    <script src={% static 'assets/bracket/lib/jquery-switchbutton/jquery.switchButton.js' %}></script>
    <script src={% static 'assets/bracket/lib/peity/jquery.peity.js' %}></script>
    <script src={% static 'assets/bracket/lib/select2/js/select2.min.js' %}></script>


    <script src={% static 'assets/bracket/js/bracket.js' %}></script>

    <!-- js Core-->
    <script src={% static 'LDCI/Core/jquery.mask.js' %}></script>
    <script src={% static 'LDCI/Core/alertify.min.js' %}></script>
    <script src={% static 'LDCI/Core/jquery.dataTables.min.js' %}></script>
    <script src={% static 'LDCI/Core/dataTables.bootstrap.min.js' %}></script>

    <script src={% static 'LDCI/Core/intlTelInput.js' %}></script>
    <script src={% static 'LDCI/Core/core.js' %}></script>
    <script src={% static 'LDCI/Core/dropzone.min.js' %}></script>
    <script src={% static 'assets/bracket/lib/parsleyjs/parsley.js' %}></script>


       <script>
             var anio = (new Date).getFullYear();
             $("#copyright").text( 'Copyright - '+anio+'. LDC. All Rights Reserved.');
       </script>
     <script src={% static 'LDCI/js/reportes.js' %}></script>
     {% block javascript %}

     {% endblock %}
  </body>
</html>

templates/braket/tabPanel.html
<div class="br-sideright">
    <!-- Tab panes -->
      <div class="tab-pane pos-absolute a-0 mg-t-60 overflow-y-auto" id="calendar" role="tabpanel">
        <label class="sidebar-label pd-x-25 mg-t-25">Fecha y Hora</label>
        <div class="pd-x-25">
          <h2 id="brTime" class="tx-white tx-lato mg-b-5"></h2>
          <h6 id="brDate" class="tx-white tx-light op-3"></h6>
        </div>

        <label class="sidebar-label pd-x-25 mg-t-25">Calendario</label>
        <div class="datepicker sidebar-datepicker"></div>
  
      </div>
  </div>

templates/catalogos/tipoTransporte.html
{% extends "braket/layout.html" %}
{%load static  %}
{% block principal %}

<div class="col-md-4">
    <div class="box box-success">
        <div class="box-heading"><h5 class="text-center">Catálogo Tipo de Transporte</h5></div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="id_TipoTransporte">Código</label>
                        <input name="id_TipoTransporte" id="id_TipoTransporte" readonly class="form-control input-sm">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="txt_nombre">Nombre</label>
                        <input name="txt_nombre" id="txt_nombre" class="form-control input-sm" type="text" maxlength="50">
                    </div>
                </div>
            </div>
        </div>
        <div class="box-footer text-right">

            <button onclick="guardar()" class="btn btn-success btn-sm" id="btnGuardarTipoTransporte">
                <i class="fa fa-save"> </i> Guardar
            </button>
            <button onclick="eliminar()" disabled class="btn btn-danger btn-sm" id="btnEliminarTipoTransporte">
                <i class="fa fa-trash-o"> </i> Eliminar
            </button>
            <a title="Limpiar formulario" href="{% url 'inventario:tipoTransporte' %}" class="btn btn-md btn-warning btn-sm" ><i class="fa fa-recycle"></i> Limpiar</a>
        </div>
    </div>
</div>

<div class="col-md-6">
    <div class="box box-success">
        <div class="box-heading">
            <div class="row"></div>
        </div>
        <div class="box-body">
            <div class="row form-group">
                <div class="col-lg-12">
                    <div id="results" class="table-responsive">
                        <table class="table" id="tblTipoTransporte">
                            <thead>
                            <tr>
                                <th>id</th>
                                <th>Nombre</th>
                                <th>Seleccione</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
<!-- js -->
{% block javascript %}
    <script src={% static 'LDCI/js/tipoTransporte.js' %}></script>
{% endblock %}

templates/login/login.html
{%load static  %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
      <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

   <!-- Meta -->
   <meta name="description" content="SISTEMA - LOGISTICA DE CARGA">
   <meta name="author" content="kennysaenz31@gmail.com">

   <title>SISTEMA - LOGISTICA DE CARGA</title>
   <link rel="icon" href={% static 'assets/bracket/Logo-Intermodal.ico' %}>

    <!-- vendor css -->
    <link rel="stylesheet" href={% static 'assets/bracket/lib/font-awesome/css/font-awesome.css' %}>
    <link rel="stylesheet" href={% static 'assets/bracket/lib/Ionicons/css/ionicons.css' %}>

    <!-- Bracket CSS -->
    <link rel="stylesheet" href={% static 'assets/bracket/css/bracket.css' %}>

     <!-- Core CSS -->
    <link rel="stylesheet" href={% static 'LDCI/Core/alertify.default.css' %}>
    <link rel="stylesheet" href={% static 'LDCI/Core/alertify.core.css' %}>
    <link rel="stylesheet" href={% static 'LDCI/Core/core.css' %}>
    <link rel="stylesheet" href={% static 'LDCI/Core/jquery-ui.min.css' %}>

    <link rel="stylesheet" href={% static 'LDCI/Core/intlTelInput.css' %}>
    <link rel="stylesheet" href={% static 'LDCI/Core/demo.css' %}>

  </head>

  <body class="bg-br-primary">

         <!--INICIO CONTENEDOR CARGANDO-->
         <div id="loader-wrapper">
          <div id="loader"></div>
          <div class="loader-section section-left"></div>
          <div class="loader-section section-right"></div>
        </div>
        <!--FIN CONTENEDOR CARGANDO-->
    <div class="row" style="display:contents;">
        <div class="d-flex align-items-center justify-content-center  ht-100v">

           <form  method="POST">
              <div class="login-wrapper wd-300 wd-xs-350 pd-25 pd-xs-40 bg-white rounded shadow-base">
                <div class="signin-logo tx-center tx-28 tx-bold tx-inverse"><span class="tx-normal">[</span> LDC <span class="tx-normal">]</span></div>
                <div class="tx-center mg-b-60">LOGISTICA DE CARGA INTERMODAL</div>

                   <div class="input-group">
                      <span class="input-group-addon"><i class="icon ion-person tx-16 lh-0 op-6"></i></span>
                      <input required type="text" id="id_username" name="username" class="form-control" placeholder="Ingrese Usuario">
                  </div>
                  <br>
                  <div class="input-group">
                      <span class="input-group-addon"><i class="icon ion-ios-locked-outline tx-16 lh-0 op-6"></i></span>
                      <input required type="password" id="id_password" name="password" class="inline-block form-control" placeholder="Ingrese Contraseña">
                  </div>
                  {% csrf_token %}

                  <br>
                <button type="submit" class="btn btn-info btn-block">Entrar</button>
                <br>
                <center><a href="InicioSesion.registro" class="optionMenu" > <label class="tx-normal">Registrarse</label></a></center>
              </div><!-- login-wrapper -->
           </form>

        </div><!-- d-flex -->
    </div>
    <footer class="br-footer">
      <div class="footer-left">
          <div class="mg-b-2" id="copyright"> </div>
      </div>
  </footer>
    <!-- js Core-->
    <script src={% static 'LDCI/Core/jquery.min.js' %}></script>
    <script src={% static 'LDCI/Core/jquery.waiting.js' %}></script>
    <script src={% static 'LDCI/Core/jquery-ui.min.js' %}></script>

    <script src={% static 'assets/bracket/lib/popper.js/popper.js' %}></script>
    <script src={% static 'assets/bracket/lib/bootstrap/bootstrap.js' %}></script>

    <script src={% static 'LDCI/Core/alertify.min.js' %}></script>
    <script src={% static 'LDCI/Core/intlTelInput.js' %}></script>
    <script src={% static 'LDCI/Core/core.js' %}></script>

      <script>

             var anio = (new Date).getFullYear();
             $("#copyright").text( 'Copyright - '+anio+'. LDCI. All Rights Reserved.');

            // Verifica si hay errores
           {% if form.errors %}

                    {% for field in form %}
                        {% if field %}
                            {% for error in field.errors %}
                            alertError('{{ error|escape }}'); //Muestra error
                            {% endfor %}
                        {% endif %}
                    {% endfor %}

                   {% if form.non_field_errors %}
                        {% for err in form.non_field_errors %}
                              alertError('{{ err }}'); //Muestra error
                        {% endfor %}
                    {% endif %}

           {% endif %}

    </script>

  </body>
</html>